model_selection:
  module_0:
    classifier: LGBMClassifier
    module: lightgbm
    params:
      n_estimators: 100
      random_state: 0
  module_1:
    classifier: XGBClassifier
    module: xgboost
    params:
      n_estimators: 50
      random_state: 0
    