number_of_feature_columns: 9

feature_columns:
  id
  Mean_Integrated
  SD
  EK
  Skewness
  Mean_DMSNR_Curve
  SD_DMSNR_Curve
  EK_DMSNR_Curve
  Skewness_DMSNR_Curve
  Class

datatype_of_columns:
 id: int64
 Mean_Integrated: float64
 SD: float64
 EK: float64
 Skewness: float64
 Mean_DMSNR_Curve: float64
 SD_DMSNR_Curve: float64
 EK_DMSNR_Curve: float64
 Skewness_DMSNR_Curve: float64
 Class: int64

target_column: Class

class_value:
  Class_0: 0
  Class_1: 1

 